name: 'Generate WP Plugin Manifest'
description: 'Generate a json file containing update info for a WP Plugin'
inputs:
  plugin-name:
    description: 'Directory name of the wordpress plugin'
    required: true
  theme-name:
    description: 'Directory name of the wordpress theme'
    required: false
  output-file:
    description: 'Path of json file to write to'
    required: true
  package-file:
    description: 'File name of the current zip archive of this wordpress plugin'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
